  LexSlotTypeLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Version 1.1 of LexSlotType Custom Resource"
      Code:
        S3Bucket: !Ref S3CodeBucket
        S3Key: !Ref CustomResourceCodeObject
      Handler: slottypehandler.handler
      Role: !GetAtt LexLambdaRole.Arn
      Runtime: nodejs12.0
      Timeout: 300

  LexIntentLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Version 1.1 of LexIntent Custom Resource"
      Code:
        S3Bucket: !Ref S3CodeBucket
        S3Key: !Ref CustomResourceCodeObject
      Handler: intenthandler.handler
      Role: !GetAtt LexLambdaRole.Arn
      Runtime: nodejs12.0
      Timeout: 300

  LexBotLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Version 1.1 of LexBot Custom Resource"
      Code:
        S3Bucket: !Ref S3CodeBucket
        S3Key: !Ref CustomResourceCodeObject
      Handler: bothandler.handler
      Role: !GetAtt LexLambdaRole.Arn
      Runtime: nodejs12.0
      Timeout: 300

  LexLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LogsForLambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
        - PolicyName: Lex
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lex:*
                Resource: '*'

Outputs:
  LambdaRoleArn:
    Description: Lambda Role Arn
    Value: !GetAtt lambdaRole.Arn
  LambdaFunctionArn:
      Description: Lambda Function Arn
      Value: !GetAtt lambdaFunction.Arn
